### ISSUE TITLE
License is incompatible with Krita's official plugin license policy

### ISSUE THREAD

**Issue by raghu-kamath** [imperator-maximus/stable-diffusion-krita#20]
You can read the official license policy for plugins here - https://krita.org/en/about/license/
The plug-in porbably needs to be under GNU GPL.

**Comment by imperator-maximus** [comment]
Hello,
are you from official Krita team?
GNU only would not be an option for me. But what about dual license GNU and MIT?

**Comment by raghu-kamath** [comment]
Hello Thanks for responding.

I am not an official representative of Krita team. I do not speak for the dev team.

The license page says it needs to be GPL.

But I asked on IRC and the devs said it can be under GNU GPL compatible license - This was their response -
" mit without extra conditions on usage is compatible with gplv3, as soon as there are usage restrictions, like "must only be used for the good of mankind" it's incompatible"

And I think your license is MIT which is compatible with GNU GPL as per the FSF - https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses. So as long as you do not place any restriction then MIT is fine I think.

Closing this issue then.

**Comment by imperator-maximus** [comment]
thank you for asking and helping me out here!👍

**Comment by raghu-kamath** [comment]
I'll keep you posted if there is any thing about this 👍

**Comment by keturn** [comment]
If you're only distributing your own code, then yeah, dual-license MIT & GPL is fine.

The problem comes up if you redistribute the Stable Diffusion model, because _that_ has use-based restrictions on it that are incompatible with the GPL.

I wrote up some questions about it here https://huggingface.co/spaces/CompVis/stable-diffusion-license/discussions/3

but I think I'll have to find somewhere else to submit that, as I don't think anyone reads that discussions board.
